version: '3'

services:
  app:
    build: .
    volumes:
       - ./:/app

  tests:
    build: .
    command: pytest -vv
    volumes:
       - ./:/app

  flake8:
    build: .
    command: flake8 .
    volumes:
       - ./:/app
